parameters:
  p_cas:
    base_url: http://127.0.0.1:8000
    protocol:
      login:
        path: /login
        query: []
        allowed_parameters:
          - service
          - renew
          - gateway
      servicevalidate:
        path: /serviceValidate
        query: []
        allowed_parameters:
          - service
          - ticket
          - pgtUrl
          - renew
          - format
      logout:
        path: /logout
        query: []
        allowed_parameters:
          - service

services:
  pcas:
    class: OpenEuropa\pcas\PCas
    arguments: ['%p_cas%', '@pcas.httpclient', '@pcas.protocol', '@session']
    public: true

  pcas.httpclient:
    class: OpenEuropa\pcas\Http\Client
    factory: 'pcas.httpclientfactory:getHttpClient'

  pcas.protocol:
    class: OpenEuropa\pcas\Cas\Protocol\V2\CasProtocolV2
    arguments: ['@pcas.userfactory', '@pcas.serializerfactory']
    public: true

  pcas.userfactory:
    class: OpenEuropa\pcas\Security\Core\User\PCasUserFactory

  pcas.serializerfactory:
    class: OpenEuropa\pcas\Utils\PCasSerializerFactory

  pcas.httpclientfactory:
    class: OpenEuropa\pcas\Http\HttpClientFactory

  session:
    synthetic: true