parameters:
  logger_startup_message: 'Logger just got started!!! (from original config)'

  protocol.login.uri: http://127.0.0.1:8000/login
  protocol.login.query: []
  protocol.login.allowed_parameters:
    - service
    - renew
    - gateway

  protocol.servicevalidate.uri: http://127.0.0.1:8000/serviceValidate
  protocol.servicevalidate.query: []
  protocol.servicevalidate.allowed_parameters:
    - service
    - ticket
    - pgtUrl
    - renew
    - format

  protocol.logout.uri: http://127.0.0.1:8000/logout
  protocol.logout.query: []
  protocol.logout.allowed_parameters:
    - service

services:
  pcas:
    class: OpenEuropa\pcas\PCas
    arguments: ['@?pcas.config', '@?pcas.httpclient', '@?pcas.protocol', '@?session']
    public: true

  pcas.httpclient:
    class: OpenEuropa\pcas\Http\Client
    factory: 'pcas.httpclientfactory:getHttpClient'

  pcas.config:
    class: OpenEuropa\pcas\Config\PcasConfig
    arguments: ['%protocol.login.uri%'
                '%protocol.login.query%'
                '%protocol.login.allowed_parameters%'
                '%protocol.logout.uri%'
                '%protocol.logout.query%'
                '%protocol.logout.allowed_parameters%'
                '%protocol.servicevalidate.uri%'
                '%protocol.servicevalidate.query%'
                '%protocol.servicevalidate.allowed_parameters%'n
                '%logger_startup_message%'
                ]
    public: true

  pcas.protocol:
    class: OpenEuropa\pcas\Cas\Protocol\V2\CasProtocolV2
    arguments: ['@pcas.userfactory', '@pcas.serializerfactory']
    public: true

  pcas.userfactory:
    class: OpenEuropa\pcas\Security\Core\User\PCasUserFactory

  pcas.serializerfactory:
    class: OpenEuropa\pcas\Utils\PCasSerializerFactory

  pcas.httpclientfactory:
    class: OpenEuropa\pcas\Http\HttpClientFactory
